/**
 * This file is auto-generated from the schema.
 * Do not edit this file directly, as your changes will be overwritten.
 */

import React from 'react';

/**
 * Common props for all segment components
 */
export interface SegmentProps {
  foreground: string;
  background: string;
  style?: 'plain' | 'diamond' | 'powerline';
  powerline_symbol?: string;
}

/**
 * Complete segment type with properties
 */
export interface SegmentType {
  type: string;
  foreground: string;
  background: string;
  style?: string;
  powerline_symbol?: string;
  properties?: Record<string, any>;

  // Added for compatibility with existing code
  config?: Record<string, any>;
}

// Generated segment config interfaces
export interface GitSegmentConfig {
  branch_icon?: string;
  display_status?: boolean;
  branch?: string;
  ahead?: number;
  behind?: number;
  dirty?: boolean;
}

export interface PathSegmentConfig {
  style?: 'folder' | 'full' | 'short';
  max_width?: number;
}

export interface TextSegmentConfig {
  text: string;
}

export interface TimeSegmentConfig {
  format?: string;
}

export interface BatterySegmentConfig {
  display_charging?: boolean;
  charging?: boolean;
}

export interface OSSegmentConfig {
  windows?: string;
  macos?: string;
  linux?: string;
}

export interface CommandSegmentConfig {
  command: string;
  shell?: string;
  args?: string[];
}

export interface ExecutionTimeSegmentConfig {
  format?: string;
  threshold?: number;
}

// Add more segment config interfaces as needed

// Map segment types to their config interfaces
export type SegmentConfigType = {
  git: GitSegmentConfig;
  path: PathSegmentConfig;
  text: TextSegmentConfig;
  time: TimeSegmentConfig;
  battery: BatterySegmentConfig;
  os: OSSegmentConfig;
  command: CommandSegmentConfig;
  executiontime: ExecutionTimeSegmentConfig;
  [key: string]: Record<string, any>;
};
