/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * https://ohmyposh.dev/docs/configuration/general#general-settings
 */
export type FinalSpace = boolean;
/**
 * https://ohmyposh.dev/docs/configuration/general#general-settings
 */
export type EnableCursorPositioning = boolean;
export type FTCSCommandMarksForShellIntegration = boolean;
/**
 * https://ohmyposh.dev/docs/configuration/general#general-settings
 */
export type EnableOSC99751 = string;
/**
 * The duration for which the segment will be cached. This is parsed using the `time.ParseDuration` function from the Go standard library (see https://pkg.go.dev/time#ParseDuration for details).
 */
export type CacheDuration = string;
/**
 * https://ohmyposh.dev/docs/configuration/general#general-settings
 */
export type PatchPowerShellColorBleed = boolean;
/**
 * https://ohmyposh.dev/docs/configuration/title#console-title-template
 */
export type ConsoleTitleTemplate = string;
/**
 * This interface was referenced by `Palette`'s JSON-Schema definition
 * via the `patternProperty` ".*".
 */
export type Color = ColorString | PaletteReference;
/**
 * https://ohmyposh.dev/docs/configuration/colors
 */
export type ColorString = string;
/**
 * https://ohmyposh.dev/docs/configuration/colors#palette
 */
export type PaletteReference = string;
/**
 * https://ohmyposh.dev/docs/configuration/block
 */
export type Block = {
  [k: string]: unknown;
} & {
  type?: BlockType;
  alignment?: BlockAlignment;
  newline?: Newline;
  leading_diamond?: LeadingDiamond;
  trailing_diamond?: TrailingDiamond;
  segments?: SegmentsListPromptElementsToDisplayBasedOnContext;
  [k: string]: unknown;
};
/**
 * https://ohmyposh.dev/docs/configuration/block#type
 */
export type BlockType = "prompt" | "rprompt";
/**
 * https://ohmyposh.dev/docs/configuration/block#alignment
 */
export type BlockAlignment = "left" | "right";
/**
 * https://ohmyposh.dev/docs/configuration/block#newline
 */
export type Newline = boolean;
/**
 * https://ohmyposh.dev/docs/configuration/block#leading-diamond
 */
export type LeadingDiamond = string;
/**
 * https://ohmyposh.dev/docs/configuration/block#trailing-diamond
 */
export type TrailingDiamond = string;
/**
 * https://ohmyposh.dev/docs/configuration/segment
 */
export type ASegment = {
  [k: string]: unknown;
};
/**
 * https://ohmyposh.dev/docs/configuration/block#segments
 */
export type SegmentsListPromptElementsToDisplayBasedOnContext = ASegment[];
/**
 * https://ohmyposh.dev/docs/configuration/general#blocks
 */
export type BlockArray = Block[];
/**
 * https://ohmyposh.dev/docs/configuration/tooltips
 */
export type TooltipListPromptElementsToDisplayBasedOnContext = ASegment[];
/**
 * https://ohmyposh.dev/docs/configuration/transient
 */
export type TransientPromptSetting = {
  filler?: Filler;
  newline?: Newline1;
  [k: string]: unknown;
};
/**
 * Right aligned filler text, will span the remaining width.
 */
export type Filler = string;
/**
 * Add a newline before the prompt
 */
export type Newline1 = boolean;
export type PromptTemplate = string;
/**
 * https://ohmyposh.dev/docs/configuration/templates
 */
export type TemplateText = string;
/**
 * https://ohmyposh.dev/docs/configuration/colors#color-templates
 */
export type AnArrayOfTemplates = TemplateText[];
/**
 * https://ohmyposh.dev/docs/configuration/colors#color-templates
 */
export type AnArrayOfTemplates1 = TemplateText[];
export type PromptTemplate1 = string;
/**
 * https://ohmyposh.dev/docs/configuration/cycle
 */
export type ListOfSettingsToCycleThroughSegmentBySegment = {
  foreground?: Color;
  background?: Color;
  [k: string]: unknown;
}[];
export type AccentColor = ColorString | PaletteReference;
export type TheITerm2FeaturesToEnable = ("prompt_mark" | "current_dir" | "remote_host")[];

/**
 * https://ohmyposh.dev/docs/configuration/general
 */
export interface TheOhMyPoshThemeDefinition {
  final_space?: FinalSpace;
  enable_cursor_positioning?: EnableCursorPositioning;
  shell_integration?: FTCSCommandMarksForShellIntegration;
  pwd?: EnableOSC99751;
  upgrade?: EnableUpgradeNotice;
  patch_pwsh_bleed?: PatchPowerShellColorBleed;
  console_title_template?: ConsoleTitleTemplate;
  terminal_background?: Color;
  blocks: BlockArray;
  tooltips?: TooltipListPromptElementsToDisplayBasedOnContext;
  transient_prompt?: TransientPromptSetting;
  valid_line?: ValidLineSettingForPowerShellOnly;
  error_line?: ErrorLineSettingForPowerShellOnly;
  secondary_prompt?: SecondaryPromptSetting;
  debug_prompt?: DebugPromptSettingForPowerShellOnly;
  palette?: Palette;
  palettes?: Palettes;
  cycle?: ListOfSettingsToCycleThroughSegmentBySegment;
  accent_color?: AccentColor;
  iterm_features?: TheITerm2FeaturesToEnable;
  var?: ConfigVariablesToUseInTemplatesCanBeAnyValue;
  [k: string]: unknown;
}
/**
 * https://ohmyposh.dev/docs/configuration/general#general-settings
 */
export interface EnableUpgradeNotice {
  interval?: CacheDuration;
  source?: "cdn" | "github";
  auto?: boolean;
  notice?: boolean;
  [k: string]: unknown;
}
/**
 * https://ohmyposh.dev/docs/configuration/line-error
 */
export interface ValidLineSettingForPowerShellOnly {
  template?: PromptTemplate;
  foreground?: Color;
  foreground_templates?: AnArrayOfTemplates;
  background?: Color;
  background_templates?: AnArrayOfTemplates1;
  [k: string]: unknown;
}
/**
 * https://ohmyposh.dev/docs/configuration/line-error
 */
export interface ErrorLineSettingForPowerShellOnly {
  template?: PromptTemplate;
  foreground?: Color;
  foreground_templates?: AnArrayOfTemplates;
  background?: Color;
  background_templates?: AnArrayOfTemplates1;
  [k: string]: unknown;
}
/**
 * https://ohmyposh.dev/docs/configuration/secondary-prompt
 */
export interface SecondaryPromptSetting {
  template?: PromptTemplate;
  foreground?: Color;
  foreground_templates?: AnArrayOfTemplates;
  background?: Color;
  background_templates?: AnArrayOfTemplates1;
  [k: string]: unknown;
}
/**
 * https://ohmyposh.dev/docs/configuration/debug-prompt
 */
export interface DebugPromptSettingForPowerShellOnly {
  template?: PromptTemplate;
  foreground?: Color;
  foreground_templates?: AnArrayOfTemplates;
  background?: Color;
  background_templates?: AnArrayOfTemplates1;
  [k: string]: unknown;
}
/**
 * https://ohmyposh.dev/docs/configuration/colors#palette
 *
 * This interface was referenced by `ListOfPalettes`'s JSON-Schema definition
 * via the `patternProperty` ".*".
 */
export interface Palette {
  [k: string]: Color;
}
/**
 * https://ohmyposh.dev/docs/configuration/colors#palettes
 */
export interface Palettes {
  template?: PromptTemplate1;
  list?: ListOfPalettes;
  [k: string]: unknown;
}
export interface ListOfPalettes {
  [k: string]: Palette;
}
/**
 * https://ohmyposh.dev/docs/configuration/templates#config-variables
 */
export interface ConfigVariablesToUseInTemplatesCanBeAnyValue {
  [k: string]: unknown;
}
